spring:
  application:
    name: sf-usermanagement
  security:
    user:
      name: disable
      password: disable
  datasource:
    url: jdbc:postgresql://ep-small-thunder-a1mbrg0k-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_vyjmQkB2Gh6P
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

server:
  port: 8081

